app:
  security:
    oauth2:
      clientId: nightfury
      secret: secret
      lifeTime: 600 # 10 minutes
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: "SevenEightTwo782"
spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081