app:
  service:
    cordelia:
      baseUrl: http://localhost:8081
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: ""
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/learn_microservice?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: SevenEightTwo782
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8083
  servlet:
    context-path: /api/dexter
