app:
  service:
    cordelia:
      baseUrl: http://cordelia:8081
redis:
  config:
    cache:
      host: redis
      port: 6379
      password: "SevenEightTwo782"
spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/learn_microservice?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: SevenEightTwo782
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8083
  servlet:
    context-path: /api/dexter