app:
  service:
    cordelia:
      baseUrl: http://cordelia:8081
      clientId: nightfury
      secret: secret
      grantType: password
    dexter:
      baseUrl: http://dexter:8083/api/dexter
redis:
  config:
    cache:
      host: redis
      port: 6379
      password: "SevenEightTwo782"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/learn_microservice?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: SevenEightTwo782
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8082
  servlet:
    context-path: /api/valkyrie